# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/top.xdc

# Block Designs: bd/take2/take2.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==take2 || ORIG_REF_NAME==take2} -quiet] -quiet

# IP: bd/take2/ip/take2_vga_driver_0_0/take2_vga_driver_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==take2_vga_driver_0_0 || ORIG_REF_NAME==take2_vga_driver_0_0} -quiet] -quiet

# IP: bd/take2/ip/take2_clk_wiz_1_1/take2_clk_wiz_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==take2_clk_wiz_1_1 || ORIG_REF_NAME==take2_clk_wiz_1_1} -quiet] -quiet

# IP: bd/take2/ip/take2_ball_0_0/take2_ball_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==take2_ball_0_0 || ORIG_REF_NAME==take2_ball_0_0} -quiet] -quiet

# IP: bd/take2/ip/take2_bricks_0_0/take2_bricks_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==take2_bricks_0_0 || ORIG_REF_NAME==take2_bricks_0_0} -quiet] -quiet

# IP: bd/take2/ip/take2_rgb_combiner_0_0/take2_rgb_combiner_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==take2_rgb_combiner_0_0 || ORIG_REF_NAME==take2_rgb_combiner_0_0} -quiet] -quiet

# IP: bd/take2/ip/take2_myip_0_0/take2_myip_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==take2_myip_0_0 || ORIG_REF_NAME==take2_myip_0_0} -quiet] -quiet

# IP: bd/take2/ip/take2_paddle_0_0/take2_paddle_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==take2_paddle_0_0 || ORIG_REF_NAME==take2_paddle_0_0} -quiet] -quiet

# IP: bd/take2/ip/take2_scoreboard_0_0/take2_scoreboard_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==take2_scoreboard_0_0 || ORIG_REF_NAME==take2_scoreboard_0_0} -quiet] -quiet

# IP: bd/take2/ip/take2_axi_gpio_0_0/take2_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==take2_axi_gpio_0_0 || ORIG_REF_NAME==take2_axi_gpio_0_0} -quiet] -quiet

# IP: bd/take2/ip/take2_axi_timer_0_0/take2_axi_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==take2_axi_timer_0_0 || ORIG_REF_NAME==take2_axi_timer_0_0} -quiet] -quiet

# IP: bd/take2/ip/take2_dlmb_v10_2/take2_dlmb_v10_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==take2_dlmb_v10_2 || ORIG_REF_NAME==take2_dlmb_v10_2} -quiet] -quiet

# IP: bd/take2/ip/take2_ilmb_v10_2/take2_ilmb_v10_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==take2_ilmb_v10_2 || ORIG_REF_NAME==take2_ilmb_v10_2} -quiet] -quiet

# IP: bd/take2/ip/take2_dlmb_bram_if_cntlr_2/take2_dlmb_bram_if_cntlr_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==take2_dlmb_bram_if_cntlr_2 || ORIG_REF_NAME==take2_dlmb_bram_if_cntlr_2} -quiet] -quiet

# IP: bd/take2/ip/take2_ilmb_bram_if_cntlr_2/take2_ilmb_bram_if_cntlr_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==take2_ilmb_bram_if_cntlr_2 || ORIG_REF_NAME==take2_ilmb_bram_if_cntlr_2} -quiet] -quiet

# IP: bd/take2/ip/take2_lmb_bram_2/take2_lmb_bram_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==take2_lmb_bram_2 || ORIG_REF_NAME==take2_lmb_bram_2} -quiet] -quiet

# IP: bd/take2/ip/take2_rst_clk_wiz_1_100M_2/take2_rst_clk_wiz_1_100M_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==take2_rst_clk_wiz_1_100M_2 || ORIG_REF_NAME==take2_rst_clk_wiz_1_100M_2} -quiet] -quiet

# IP: bd/take2/ip/take2_xbar_1/take2_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==take2_xbar_1 || ORIG_REF_NAME==take2_xbar_1} -quiet] -quiet

# IP: bd/take2/ip/take2_microblaze_0_axi_periph_1/take2_microblaze_0_axi_periph_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==take2_microblaze_0_axi_periph_1 || ORIG_REF_NAME==take2_microblaze_0_axi_periph_1} -quiet] -quiet

# IP: bd/take2/ip/take2_microblaze_0_2/take2_microblaze_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==take2_microblaze_0_2 || ORIG_REF_NAME==take2_microblaze_0_2} -quiet] -quiet

# IP: bd/take2/ip/take2_mdm_1_2/take2_mdm_1_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==take2_mdm_1_2 || ORIG_REF_NAME==take2_mdm_1_2} -quiet] -quiet

# IP: bd/take2/ip/take2_auto_pc_0/take2_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==take2_auto_pc_0 || ORIG_REF_NAME==take2_auto_pc_0} -quiet] -quiet

# XDC: c:/Users/jsullivan4/video_test/video_test.gen/sources_1/bd/take2/take2_ooc.xdc
