# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/jsullivan4/video_test/video_test.srcs/sources_1/bd/take2/ip/take2_rst_clk_wiz_1_100M_2/take2_rst_clk_wiz_1_100M_2.xci
# IP: The module: 'take2_rst_clk_wiz_1_100M_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jsullivan4/video_test/video_test.gen/sources_1/bd/take2/ip/take2_rst_clk_wiz_1_100M_2/take2_rst_clk_wiz_1_100M_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'take2_rst_clk_wiz_1_100M_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/jsullivan4/video_test/video_test.gen/sources_1/bd/take2/ip/take2_rst_clk_wiz_1_100M_2/take2_rst_clk_wiz_1_100M_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'take2_rst_clk_wiz_1_100M_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/jsullivan4/video_test/video_test.gen/sources_1/bd/take2/ip/take2_rst_clk_wiz_1_100M_2/take2_rst_clk_wiz_1_100M_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'take2_rst_clk_wiz_1_100M_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/jsullivan4/video_test/video_test.srcs/sources_1/bd/take2/ip/take2_rst_clk_wiz_1_100M_2/take2_rst_clk_wiz_1_100M_2.xci
# IP: The module: 'take2_rst_clk_wiz_1_100M_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jsullivan4/video_test/video_test.gen/sources_1/bd/take2/ip/take2_rst_clk_wiz_1_100M_2/take2_rst_clk_wiz_1_100M_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'take2_rst_clk_wiz_1_100M_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/jsullivan4/video_test/video_test.gen/sources_1/bd/take2/ip/take2_rst_clk_wiz_1_100M_2/take2_rst_clk_wiz_1_100M_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'take2_rst_clk_wiz_1_100M_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/jsullivan4/video_test/video_test.gen/sources_1/bd/take2/ip/take2_rst_clk_wiz_1_100M_2/take2_rst_clk_wiz_1_100M_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'take2_rst_clk_wiz_1_100M_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
