# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/jsullivan4/video_test/video_test.srcs/sources_1/bd/take2/ip/take2_auto_pc_0/take2_auto_pc_0.xci
# IP: The module: 'take2_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jsullivan4/video_test/video_test.gen/sources_1/bd/take2/ip/take2_auto_pc_0/take2_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'take2_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/jsullivan4/video_test/video_test.srcs/sources_1/bd/take2/ip/take2_auto_pc_0/take2_auto_pc_0.xci
# IP: The module: 'take2_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jsullivan4/video_test/video_test.gen/sources_1/bd/take2/ip/take2_auto_pc_0/take2_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'take2_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
